### ISSUE TITLE
Create Atoms Documentation

### ISSUE THREAD

**Issue by smjanke** [NQCD/NonadiabaticMolecularDynamics.jl#101]
https://github.com/NQCD/NonadiabaticMolecularDynamics.jl/blob/3132608e9ee40331f6e72ea578abc4ef8887cd0e/docs/src/getting_started.md#L11

Very good basic description!
It still needs a bit extension, mainly:
- how can you define a large array of atomic positions, e.g. for 56 Au atoms? I remember from working with the code that it was a bit more complicated than just passing the atom-label into an array and writing it all by hand would be very cumbersome.
- how could you read in a file with already existing geometries? (This could also reference to another page)

**Comment by jamesgardner1421** [comment]
This is a good point, I had mostly forgotten about this. I'll definitely create a page on input and output.

So far I've been hesitant to elaborate on this stuff too much since there was talk amongst the JuliaMolSim community of creating a unified interface for atomic structures to allow for easy IO and transferability between different packages. I was hoping to use this to save us some work but it seems this might take some time to appear still.

Long term I would still like to use this interface but since it's taking a while I can try to fill in the gaps while we wait.

**Comment by smjanke** [comment]
It would indeed be pretty cool to use the JuliaMolSim interface when it's out! 
I think for the time being, elaborating will still be useful, because defining atoms is something everyone will need to do and if we want to convince anyone else to use the code, getting started needs to be as easy as possible.
